package main.java.gui;

import main.java.agents.ServerAgent;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Jakub Fortunka on 08.11.14.
 */
public class MainFrame extends JFrame {

    private JPanel rootPanel;
    private JPanel optionsPanel;
    private JSplitPane splitPanel;
    private BoardPanel boardPanel;

    private ServerAgent server;

    public MainFrame(ServerAgent s) {

        setTitle("Battle!");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        setContentPane(rootPanel);

        server = s;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(2, 2, 2, 2), -1, -1));
        splitPanel = new JSplitPane();
        splitPanel.setOrientation(0);
        rootPanel.add(splitPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        optionsPanel = new JPanel();
        optionsPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        splitPanel.setRightComponent(optionsPanel);
        boardPanel = new BoardPanel();
        splitPanel.setLeftComponent(boardPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
